local exportLocale = os.getenv("POB_EXPORT_LOCALE")

local function normaliseLocaleId(locale)
	return locale and locale:lower():gsub("[_%-%s]", "") or nil
end

local function normalizeId(id)
	id = tostring(id)
	return id:gsub("_+$", "")
end

local function cleanAndSplit(str)
	str = str:gsub("\r\n", "\n")
	str = str:gsub("<default>", "\n^8")

	local lines = {}
	for line in str:gmatch("[^\n]+") do
		line = line:match("^%s*(.-)%s*$")
		if line ~= "" then
			line = line:gsub("%{(.-)%}", "%1")
			line = line:gsub("<<(.-)>>", "")
			line = line:match("^%s*(.-)%s*$")
			line = line:gsub('"', '\\"')
			if line ~= "" then
				table.insert(lines, line)
			end
		end
	end

	return lines
end

exportLocale = normaliseLocaleId(exportLocale)
if not exportLocale or exportLocale == "en" then
	print("Skipping unique locale export; POB_EXPORT_LOCALE is not set to a non-English locale.")
	return
end

local englishFlavour = LoadModule("../Data/FlavourText")
local localizedById = { }
local flavourTextById = { }

for row in dat("UniqueStashLayout"):Rows() do
	local localizedName = row.WordsKey.Text2
	local id = normalizeId(row.ItemVisualIdentity.Id)
	if not id:find("Map")
		and not id:find("AlternateArt")
		and not id:find("AtlasUpgrade")
		and not id:find("HeistQuest") then
		localizedById[id] = localizedById[id] or { }
		localizedById[id].name = localizedName
	end
end

for row in dat("FlavourText"):Rows() do
	local id = normalizeId(row.Id)
	flavourTextById[id] = cleanAndSplit(tostring(row.Text))
end

for id, entry in pairs(localizedById) do
	if flavourTextById[id] then
		entry.text = flavourTextById[id]
	end
end

local overlay = { }
for _, entry in ipairs(englishFlavour) do
	local localized = localizedById[normalizeId(entry.id)]
	if localized then
		local overlayEntry = overlay[entry.name] or { name = localized.name, text = { } }
		overlayEntry.name = localized.name or overlayEntry.name
		if localized.text then
			overlayEntry.text[entry.id] = localized.text
		end
		overlay[entry.name] = overlayEntry
	end
end

MakeDir("../Data/Locales")
MakeDir("../Data/Locales/"..exportLocale)

local out = io.open("../Data/Locales/"..exportLocale.."/UniqueItems.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Official unique item localisation data (c) Grinding Gear Games\n\nreturn ')
writeLuaTable(out, overlay, 1)
out:close()

print("Unique item locale overlay exported.")
